# Generated by Django 5.2.4 on 2025-07-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartpark", "0003_customuser_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_plate", models.CharField(max_length=15)),
                ("is_free", models.BooleanField(default=False)),
                ("is_special_taxi", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "db_table": "cars",
            },
        ),
        migrations.DeleteModel(
            name="BannedPlate",
        ),
        migrations.AlterUniqueTogether(
            name="dailytaxipayment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dailytaxipayment",
            name="taxi",
        ),
        migrations.DeleteModel(
            name="FreePlate",
        ),
        migrations.DeleteModel(
            name="DailyTaxiPayment",
        ),
        migrations.DeleteModel(
            name="SpecialTaxi",
        ),
    ]
