# Generated by Django 5.2.4 on 2025-07-18 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smartpark", "0006_vehicleentry_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicleentry",
            name="is_deleted",
        ),
    ]
